apiVersion: 1
datasources:
  - name: Nodease Prometheus
    uid: nodease-prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: false
    editable: true
    jsonData:
      httpMethod: POST
      timeInterval: 15s
  - name: Nodease Loki
    uid: nodease-loki
    type: loki
    access: proxy
    url: http://loki:3100
    isDefault: false
    editable: true
    jsonData:
      maxLines: 1000
